### ISSUE TITLE
read command RESULT

### ISSUE THREAD

**Issue by fmarzocca** [DaveMDS/node-red-contrib-tasmota#24]
Hi,

I am sending to my tasmota device this command, in order to get the "mem" variables:

`cmnd/<topic>/mem`

The message is correctly sent to the device, but I have no output from the switch node. How can I get the mem variables in my flow?

**Comment by DaveMDS** [comment]
Hi, sorry for the late reply, I have been very busy lately.

What you want is not possible at the moment with the tasmota nodes, the problem is that custom commands can be replayed by tasmota with different type of messages and there is no way (I know of) to understand that the msg is a reply for the custom command sent.

The only way in my mind to fix this issue is to create a new node type (eg. Tasmota Generic Node) that can send any given command it receive and will forward to output any msg received from the device. Can this be a good solution for your use case?

**Comment by DaveMDS** [comment]
I just pushed a new Generic node, that is able to send and receive any command/messages to any tasmota device.
This has been so easy to implement and is so much powerful that I don't know why I didn't do it earlier :)

Really thanks for the report
Ciao :)
Davide

**Comment by fmarzocca** [comment]
Thnak you! Waiting for the node to get updated.

**Comment by fmarzocca** [comment]
When this release will be available in the node? I am waiting for the update...

**Comment by DaveMDS** [comment]
It's already available in the 0.9.9 release :)

NOTE: give a look at the Changelog and the issue #26 !  After the upgrade you need to reconfigure ALL your deployed Tasmota nodes.

You will find a new GenericTasmota node that should be able to do what you need, let me know...

**Comment by fmarzocca** [comment]
I have 0.9.7 installed and the node is not claiming for an upgrade

![Schermata 2021-04-13 alle 20 28 42](https://user-images.githubusercontent.com/8530030/114602459-eb33cc80-9c96-11eb-95e9-aeb1c797f4ac.png)

**Comment by DaveMDS** [comment]
Dunno why... me and other people upgraded the nodes from the UI...
Is your NodeRed instance connected to internet? 
maybe try to restart NodeRed or reload the browser...

The current published version is 0.9.9 as per:
https://flows.nodered.org/node/node-red-contrib-tasmota

**Comment by fmarzocca** [comment]
NodeRed correctly working. Restarted yesterday to upgrade to latest version. No upgrade for your node is showing.
Never mind, I fixed with mqtt node.
