### ISSUE TITLE
connecting to Broker fail

### ISSUE THREAD

**Issue by Ianknx** [DaveMDS/node-red-contrib-tasmota#25]
Hello

I have been trying to configure the sensor node to connect to an online Broker and whilst the Node Red MQTT nodes configure and run there is no way I or the Broker support can figure how to connect.

I presume the connection fails on the topic as the same security is used as with the Node Red MQTT node there is also a connection from my mobile on the Tasmota platform in operation.

I have tried with three separate Node red terminals on differing machines 2 on differing RPI and one on windows to no avail.

Error: Connection refused: Server unavailable
    at MqttClient._handleConnack (C:\Users\Ian\.node-red\node_modules\mqtt\lib\client.js:920:15)
    at MqttClient._handlePacket (C:\Users\Ian\.node-red\node_modules\mqtt\lib\client.js:350:12)
    at work (C:\Users\Ian\.node-red\node_modules\mqtt\lib\client.js:292:12)
    at Writable.writable._write (C:\Users\Ian\.node-red\node_modules\mqtt\lib\client.js:302:5)
    at doWrite (C:\Users\Ian\.node-red\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Ian\.node-red\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (C:\Users\Ian\.node-red\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (node:internal/streams/readable:750:22)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12) {
  code: 3

Any help, advice or assistance greatly appreciated.

Regards

Ian

**Comment by DaveMDS** [comment]
I did not understand if you can successfully use the standard Node Red MQTT node with your online broker

**Comment by Ianknx** [comment]
Hello Dave

This is precisely the problem, the screenshot shows the problem with both
nodes using the same credentials and the broker set for multiple
connections!!!

Regards

Ian

**Comment by DaveMDS** [comment]
Screenshot? I cannot see any screenshot ... :/

**Comment by Ianknx** [comment]
screenshot as an attachment

**Comment by DaveMDS** [comment]
There are no attachments here, please use the github site and not the email reply function
https://github.com/DaveMDS/node-red-contrib-tasmota/issues/25

**Comment by Ianknx** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/31249487/112184953-a5d03200-8bf7-11eb-98ae-60a0134b35dc.png)

**Comment by DaveMDS** [comment]
OK, now I can see the image :)

To understand what is going wrong I need (at least) to see the configuration for both nodes, 
can you show me the two config pages please?

**Comment by Ianknx** [comment]
My apologies just getting to know GitHub

**Comment by Ianknx** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/31249487/112196038-84287800-8c02-11eb-9600-7f4ae273e893.png)
![Screenshot (33)](https://user-images.githubusercontent.com/31249487/112196219-b89c3400-8c02-11eb-9ded-b2c9e01822fb.png)
![Screenshot (34)](https://user-images.githubusercontent.com/31249487/112196225-b934ca80-8c02-11eb-8230-a2ab52a11768.png)
![Screenshot (32)](https://user-images.githubusercontent.com/31249487/112196230-b9cd6100-8c02-11eb-86f3-5bb7451b794b.png)

**Comment by Ianknx** [comment]
please let me know if you need any more

**Comment by Ianknx** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/31249487/112198316-e4201e00-8c04-11eb-86cc-6307b9e024f0.png)

**Comment by DaveMDS** [comment]
1. In the Tasmota sensor node configuration (second image) the `Device` field is wrong, it should be just `DHT11`
2. In the broker config the `ClientID` you wrote is a bit misleading, it should be a UNIQUE identifier (of your choice) for your client (node-red in this case), it must be unique for each connection (or you can probably leave it blank)

**Comment by Ianknx** [comment]
Hello Dave
I have followed your suggestions, I reduced everything down to one device on the server with an ID of DHT11 I then followed your advice to connect to the device as follows:-
![Screenshot (36)](https://user-images.githubusercontent.com/31249487/112300846-3444c200-8c91-11eb-8c46-944a547f682b.png)

![Screenshot (37)](https://user-images.githubusercontent.com/31249487/112300910-4aeb1900-8c91-11eb-9581-f7f66f583271.png)

![Screenshot (39)](https://user-images.githubusercontent.com/31249487/112300984-61917000-8c91-11eb-8f66-aa661dae98c5.png)

![Screenshot (38)](https://user-images.githubusercontent.com/31249487/112300946-550d1780-8c91-11eb-8b36-f9b3bd1a8a2f.png)
![Screenshot (39)](https://user-images.githubusercontent.com/31249487/112301049-77069a00-8c91-11eb-92db-b96f7ecdde88.png)
![Screenshot (40)](https://user-images.githubusercontent.com/31249487/112301070-7d951180-8c91-11eb-889b-3358ec2f3f71.png)

**Comment by Ianknx** [comment]
As you can see I tried both with and without the client ID as suggested to no avail, the normal Node Red MQTT node is still making the connections using the same server credentials.

Thanks for your assistance in this.

Ian

**Comment by DaveMDS** [comment]
Now your config seems correct to me, there should be something else going on...
I'm trying to use your online broker (I never used one as I have a local one) to see if I can find the issue,
this will take some time, please stay tuned and have patience :)

**Comment by Ianknx** [comment]
Many thanks it will be interesting to see if you have the same issue, I have been contacting support at the broker who cannot find any problems there end.

**Comment by Ianknx** [comment]
The broker offers a free package.

**Comment by DaveMDS** [comment]
Yep, I subscribed the free plan, made some tests, and found the issue! 
The problem is indeed in the ClientID used because the online broker check the correctness of that field.

The real issue is in the tasmota nodes, that prepend the string `Tasmota_` to the ClientID you specify in the config. This is needed because the tasmota nodes reuse the same mqtt configuration but perform another mqtt connection to the broker.

So when you use a standard mqqt node and a tasmota node with the same mqtt configuration what happend under the hood is that 2 different connections are made to the broker, one with the `ClientID` you gave in configuration and one with the prefix `Tasmota_` prepended. At the end your broker receive a connection from a client `Tasmota_XXX` that is unknow.

A simple workaround is to create another "Device" in the online broker with the `ClientID` modificated. es:
![broker](https://user-images.githubusercontent.com/52688/112466311-041b2300-8d66-11eb-8ecc-fcdd9a8291db.png)
![NodeRed](https://user-images.githubusercontent.com/52688/112466879-a1765700-8d66-11eb-8aac-78a5914fa0a5.png)
![Tasmota](https://user-images.githubusercontent.com/52688/112467635-97a12380-8d67-11eb-9993-06c23425e75e.png)


As you can see I created 3 Devices in the online broker (and thus 3 accepted ClientID):
 * one used in the tasmota device itself (clientid=TasmotaDevice)
 * one used from the standard mqtt node (clientid=NodeRED)
 * and one used from the tasmota nodes (clientid=Tasmota_NodeRED)

This way it works, but I need to find a real solution to this problem....

**Comment by Ianknx** [comment]
Awesome, thanks!

**Comment by Ianknx** [comment]
Hello Dave

I have been playing all morning trying to make a connection with the Tasmota SENSOR node but still cannot make things work, could you post an image of your working Tasmota set up please.

Regards

Ian

**Comment by DaveMDS** [comment]
This is the configuration of the TasmotaSensorNode, with the 3 shoot I uploaded before you should have all needed info,
let me know if you need more
![TasmotaSensorNode](https://user-images.githubusercontent.com/52688/112489785-1190d700-8d7f-11eb-921d-cb05fe0e93d3.png)

**Comment by Ianknx** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/31249487/112504544-caf1ab80-8d83-11eb-9a04-6f5e05131ca9.png)
![Screenshot (42)](https://user-images.githubusercontent.com/31249487/112504567-d2b15000-8d83-11eb-9ff5-58a92dab6491.png)
![Screenshot (43)](https://user-images.githubusercontent.com/31249487/112504596-d9d85e00-8d83-11eb-8e5f-a4275eb3c535.png)
![Screenshot (44)](https://user-images.githubusercontent.com/31249487/112504621-dfce3f00-8d83-11eb-9e83-e369723922f1.png)

**Comment by Ianknx** [comment]
Confused.

**Comment by Ianknx** [comment]
![Screenshot (45)](https://user-images.githubusercontent.com/31249487/112505159-6d119380-8d84-11eb-8242-af3e7a4547c0.png)

**Comment by DaveMDS** [comment]
In the mqtt-broker node configuration the `ClientID` should be just `NodeRed`, not `Tasmota_NodeRed` because the 
tasmota nodes already add the `Tasmota_` prefix (that is the root cause of all the problems)

Now your online broker is receiving a `ClientID` like `Tasmota_Tasmota_NodeRED` and it reject the connection

**Comment by Ianknx** [comment]
Hello Dave 

Still no closer this end, would it be possible to copy the sketch so that I can upload it into NodeRed, at least this way I can eliminate my own fummblings.

I understand what you are saying and as to what the problem is and have relayed your comments to support at the broker to see what there take on the issue is, one would have thought that complications with a world MQTT player like Tasmota should not throw up so many problems.

Regards
Ian

**Comment by DaveMDS** [comment]
Sorry but I can't upload the sketch... or better it does not work also if I do, there are the configuration mqtt node and some password involved. In this case the usual node-red copy-paste do not work.

The screenshots I posted should contain all the info needed to replicate my functional use-case, I suggest you to start again with a clean NodeRed flow, put in just the TasmotaSensorNode (no other mqtt stuff) and try to configure it again

Otherwise just give me the time to find a suitable solution.

PS: do you really need an online broker? Installing a local mqtt broker is a lot simpler (zero configuration involved), while 
the setup of your online broker is quite complex and require a deeper understand of how mqtt works, and how they implemented the online interface

**Comment by Ianknx** [comment]
Hello Dave

Thanks for the tip, The Idea is to set up a remote station some miles from
my address so I need to have an online broker to achieve this.

I will crack on with this tomorrow to see if I can get your set up working,
where are you located BTW myself in UK.

Regards

Ian

**Comment by Ianknx** [comment]
HI

Opened up Node Red this morning to find the Tasmota Node was online and running ...... wonderful thing technology.

**Comment by DaveMDS** [comment]
This is not fixed yet, you just applied a temporary workaround :)
I will keep the issue opened until a find a suitable solution

**Comment by Ianknx** [comment]
OK no problems

**Comment by DaveMDS** [comment]
This bug has been solved 2 years ago, if you are using recent software you cannot be affected by this one

**Comment by Pixelplanet** [comment]
i just had the same Problem and the only way to solve it was to delete all MQTT related nodes and configs from Node red and then reconfigure this one.
Been fighting with this for hours and that finally fixed it for now.
