### ISSUE TITLE
problems with node-red 2.0.5

### ISSUE THREAD

**Issue by fromCologne** [DaveMDS/node-red-contrib-tasmota#28]
After upgrade to Node-Red 2.0.5 all tasmota nodes lost their MQTT-Broker relationship.
If I open the config of the node there is no dropdown list to choose broker from.

**Comment by DaveMDS** [comment]
What is the Tasmota Node version?

**Comment by fromCologne** [comment]
Hi Dave,
I use node-red-contrib-tasmota 0.9.9.
After the first start of the new version node-red (2.0.5 docker), under all tasmota nodes was a hint "wrong config".
I opened the node configuration and their was the mqtt brocker lost. There was an orange field to set a new configuration node. After two restarts of node-red there appears a dropdown menue with my mqtt broker. But I had to reconfigure each tasmota node because all had the "wrong config" hint. After choosing my mqtt broker the nodes connected and were working again.
I have *two* active mqtt broker. Maybe that causes trouble with the tasmota node?
Regards
Ingo

**Comment by DaveMDS** [comment]
Indeed the 0.9.9 version have changed the broker-config code, and the "wrong config" on all node is expected,
as per changelog:
https://github.com/DaveMDS/node-red-contrib-tasmota/blob/master/CHANGELOG.md

**Comment by DaveMDS** [comment]
@alfakenzo To fix the issue described earlier you just need to save again all your nodes configuration.
I suggest to try removing all the tasmota nodes (and config) and create new ones, but to be honest your issue doesn't seems to be ralated to this one.

I can help you but I need more info about your configuration and setup.

**Comment by alfakenzo** [comment]
Tell me what you need o Infos? Update Yesterday from 1.1.4 to 2.0.5. tasmota version 0.99. I used to connect to my broker same rpi 127.0.0.1, localhost and the IP. Nothing happen

**Comment by DaveMDS** [comment]
Please show me (with screenshots) your node and broker config.
You should also see some info, maybe some errors, in the NodeRed debug panel or in the nodered output

**Comment by alfakenzo** [comment]
28.8.2021, 09:42:29node: 7f93cbc1eb95c221
msg : error
"Error: connect ECONNREFUSED 192.168.133.25:1883
This I see when I choose my IP. When I choose 127.0.0.1 the the Noe is only offline

**Comment by DaveMDS** [comment]
ECONNREFUSED means your broker did not accept the connection, check the mosquito logs

**Comment by alfakenzo** [comment]
i have this error in the log from mosquitto 1630102002: New connection from 127.0.0.1:50966 on port 1883.
1630102002: Client <unknown> disconnected due to protocol error.
1630102062: New connection from 127.0.0.1:51478 on port 1883.
1630102062: Client <unknown> disconnected due to protocol error.
1630102090: Client mqtt_cdc634f.e6727c8 disconnected.
1630102097: New connection from 127.0.0.1:51746 on port 1883.
1630102097: New client connected from 127.0.0.1:51746 as mqtt_e9c32191.ad3d7 (p$
1630102122: New connection from 127.0.0.1:52174 on port 1883.
1630102122: Client <unknown> disconnected due to protocol error.
1630102182: New connection from 127.0.0.1:52684 on port 1883.
1630102182: Client <unknown> disconnected due to protocol error.

**Comment by alfakenzo** [comment]
HI DaveMDS could it be that on 0.99 has a own mqtt-broker? And i must change the device id of the original nodered mqtt-broker?

**Comment by alfakenzo** [comment]
Solved the problems. Need now to set device ID names.

**Comment by DaveMDS** [comment]
Indeed the 0.99 release has an own mqtt-broker, that was the braking change.
Happy you solved your issue :)
