### ISSUE TITLE
Switch Node doesn't accept blank payload to query status

### ISSUE THREAD

**Issue by GeoffNT** [DaveMDS/node-red-contrib-tasmota#29]
The Tasmota MQTT spec says that sending a blank payload gives the current status of the device. This works using the standard Node Red MQTT nodes but when I try it with this node it gives "Invalid payload received on input" error. I find being able to query a device's current status useful in some logic so miss this facility. Would it be possible to add this feature?

**Comment by DaveMDS** [comment]
What version are you using? 0.9.10 used to have the bug you described.
If instead you are using 0.9.11 then I need more detailed info about how are you sending and the error you receive

**Comment by GeoffNT** [comment]
I'm using 0.9.11 
I only installed it yesterday.

I'm sending a msg.payload of a blank string to a switch node and get the message "Invalid payload received on input" in the debug pane.

If I send a msg.payload of string "on", "off" or "toggle" to the same switch node it switches the device perfectly and I get a message true or false in the debug pane

**Comment by DaveMDS** [comment]
This is the expected and documented behavior of the switch node, the output of the node is always in sync with the real state of the device, thus what you are trying to do should not be needed.

btw, if you really need to request the state again you can send a custom command as documented here:
https://github.com/DaveMDS/node-red-contrib-tasmota#send-custom-tasmota-commands

RTFM  :)

**Comment by GeoffNT** [comment]
Well you say RTFM but in the Tasmota MQTT documentation (https://tasmota.github.io/docs/Commands/) it states:

"How to use commands~
**Every command used without a parameter (payload) returns the current setting.**

Commands over MQTT are issued by using topic cmnd/%topic%/<command> and payload <parameter> where %topic% is the topic of the device you're sending the command to. **If there is no parameter (an empty MQTT message/payload), a query is sent for current status of the command**."_

That is also how the standard Node Red MQTT nodes work- sending a msg.payload of blank returns the current status.

I am new to MQTT (most of my Node Red logic currently works with Hubitat devices) but in my logic flows I often want to know what state Device A is in as part of a rule for what to do with Device B. 

For MQTT Unless you store every device's current status in a global variable, I don't see how you would achieve that without dynamically checking the status of Device A when the rule for Device B runs.

Maybe I am missing something obvious?

**Comment by DaveMDS** [comment]
yes, you are reading the wrong manual :)
I'm referring to the manual of this project, not the tasmota one

The whole point of this set of nodes is to simplify the usage for node-red users, that don't need to know/learn the tasmota commands/protocol to use them, otherwise there would have been no difference with the standard MQTT node.

To use the nodes in this repo you just need to read the briefing explanations in the home page:
https://github.com/DaveMDS/node-red-contrib-tasmota
and the inline documentation inside the nodered editor for each node, fe:
![switch](https://user-images.githubusercontent.com/52688/143308830-6e64d2aa-8320-4cbd-a3ed-c23af9ee80d9.png)

If you instead prefer to use the "raw" tasmota MQTT commands (the one documented on the tasmota site that you are referring)
you can use the TasmotaGenericNode or the standard mqtt node

PS: rtfm is a developer joke, don't take it the wrong way ;)

**Comment by GeoffNT** [comment]
It's fine, I get the RTFM joke, no offence taken. 

If you re-read my initial post I wasn't reporting a bug as such I was just asking if that feature could be added (maybe this wasn't the right place to post it?) 

I prefer your nodes over the standard Node Red MQTT ones as I like having the current status of the device showing under the nodes for clarity when debugging flows etc.

I understand that you are trying to simplify the process for people but I still think some sort of option for getting the current status in the switch node would be beneficial. Maybe have a  msg.payload of "status" returning the current status? Maybe my use case is unique but what about when Node Red starts up? I have many instances in my current setup of checking the status of various devices at start up and would use this to do the same with my Tasmota MQTT devices.   

I have tried the TasmotaGenericNode and that does work for getting status, but it doesn't seem quite as "clean" a solution as having the option directly into the switch node. 

I think part of my problem is that I have got into a method of doing things with my Hubitat devices, where I can query their status and/or issue commands to them easily, that I'm not sure how that translates to MQTT.

**Comment by DaveMDS** [comment]
Yes, this is the right place for helping issue like this one.

What I'm trying to say is that you should never need to manually request the switch state from the Tasmota Nodes,
because the nodes already done this for you. 

On node-red startup/restart the nodes automatically request the state from the device and send a msg to the output with the current state. The same happens when your tasmota device goes online/offline. This is all done automatically by the switch node for you.

Having said that, you can always request the current status of the Switch using the "command mode" that all the Tasmota Nodes provide, just send a msg with topic: "command" and payload: "POWER" to request the current state, es:
![immagine](https://user-images.githubusercontent.com/52688/143391493-4e5932ab-daec-4dc0-8dc2-abacefac9314.png)

**Comment by GeoffNT** [comment]
I hadn't realised that about the startup/restart automatic update, that is really useful.

Also the example you give of using the command mode gives me exactly what I asked for.

Thanks for all of you help

**Comment by DaveMDS** [comment]
Cool :)
